In [1]:
import numpy as np

In [4]:
# x = np.array([1,2,3])
# x

# Sorting Array

In [7]:
x = np.array([2,1,4,3,5], dtype=int)
x.sort()
x

array([1, 2, 3, 4, 5])

In [8]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [9]:
# np.argsort function return the indices of the sorted elements
f = np.array([2,1,4,3,5], dtype=int)
i = np.argsort(f)
print(i)

# NB: arg always return the index... be it argmax or argmin aor argsort etc.

[1 0 3 2 4]


In [10]:
# the indices can then be use as fancy index to get the sorted array
f[i]

array([1, 2, 3, 4, 5])

 # Sorting along row and column

In [13]:
x = np.random.randint(0,10, (4,6))
x

array([[7, 5, 3, 8, 3, 6],
       [1, 9, 0, 2, 5, 6],
       [5, 5, 5, 1, 6, 2],
       [6, 4, 4, 4, 7, 8]])

In [14]:
#sorting each column of x
np.sort(x, axis=0)

array([[1, 4, 0, 1, 3, 2],
       [5, 5, 3, 2, 5, 6],
       [6, 5, 4, 4, 6, 6],
       [7, 9, 5, 8, 7, 8]])

In [15]:
#sorting each row of x
np.sort(x, axis=1)

array([[3, 3, 5, 6, 7, 8],
       [0, 1, 2, 5, 6, 9],
       [1, 2, 5, 5, 5, 6],
       [4, 4, 4, 6, 7, 8]])

partial sorting : partitioning

In [16]:
y = np.array([7,2,3,1,6,5,4])

# give us the three smallest value in the array
np.partition(y,3)

# it will return it in no particular order "2,1,3"

array([2, 1, 3, 4, 6, 5, 7])

In [17]:
y = np.array([7,2,3,1,6,5,4])

# give us the four smallest value in the array
np.partition(y,4)

array([2, 1, 3, 4, 5, 6, 7])

In [18]:
# give us the first two smallest value of each row in the array
np.partition(x, 2, axis=1)

array([[3, 3, 5, 8, 7, 6],
       [0, 1, 2, 9, 5, 6],
       [1, 2, 5, 5, 6, 5],
       [4, 4, 4, 6, 7, 8]])

In [22]:
# we can also partition on array of strings 
name = ['sunday', 'adeola', 'charles', 'promise', 'moses', 'thomeson', 'nana', 'bosede']
name

['sunday',
 'adeola',
 'charles',
 'promise',
 'moses',
 'thomeson',
 'nana',
 'bosede']

In [23]:
# give us the first three names in their alphabetical order
np.partition(name, 3)

array(['adeola', 'bosede', 'charles', 'moses', 'nana', 'promise',
       'sunday', 'thomeson'], dtype='<U8')

# Numpy's Structured Arrays

In [25]:
npdata = [('Sunday', 22, 56, 'js1'), ('Charse', 34, 67,'ss2'), ('Mary', 36, 65, 'ss3')]

npdtype = [('Name', np.str_, 10), ('Age', np.int16), ('Score', np.float64), ('Class', np.str_, 4)]


# ('Name', np.str_, 10) is the properties of 'sunday'.... the 10 rep that the name must not be more than 10
# ('Age', np.int16) is the properties of 22
# ('Score', np.float64) is the properties of 56
# ('Class', np.str_, 4) is the properties of 'js1'
# same thing applied to others


student_record = np.array([npdata], dtype=npdtype)

print(student_record)

[[('Sunday', 22, 56., 'js1') ('Charse', 34, 67., 'ss2')
  ('Mary', 36, 65., 'ss3')]]


In [26]:
student_record['Name']


array([['Sunday', 'Charse', 'Mary']], dtype='<U10')

In [27]:
student_record[:1]


array([[('Sunday', 22, 56., 'js1'), ('Charse', 34, 67., 'ss2'),
        ('Mary', 36, 65., 'ss3')]],
      dtype=[('Name', '<U10'), ('Age', '<i2'), ('Score', '<f8'), ('Class', '<U4')])

In [28]:
np.sort(student_record, order=['Name','Score'])


array([[('Charse', 34, 67., 'ss2'), ('Mary', 36, 65., 'ss3'),
        ('Sunday', 22, 56., 'js1')]],
      dtype=[('Name', '<U10'), ('Age', '<i2'), ('Score', '<f8'), ('Class', '<U4')])