In [1]:
import numpy as np

attribute of nd array

In [4]:
a = np.arange(15).reshape(3,5)

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# To get attribute shape 
a.shape

(3, 5)

In [6]:
# To get the dimensions
a.ndim

2

In [7]:
# To find the datatype
a.dtype

dtype('int32')

In [8]:
a.dtype.name

'int32'

In [9]:
# To get the item sizes
a.itemsize

4

In [10]:
# To check the type array a is
type(a)

numpy.ndarray

In [11]:
# to find the lenght of the array
len(a)

3

In [12]:
# creating an array from a python list

a = np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int32')

In [14]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [15]:
# creating an array from a sequence of sequence
b = np.array([(1.5,2,3), (4,5,6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
c = np.array([[1,2], [3,4]], dtype=float)
c

array([[1., 2.],
       [3., 4.]])

In [17]:
np.array([1,2,3,'6',False,3.5], dtype='int32')

array([1, 2, 3, 6, 0, 3])

In [19]:
np.array(['name', 'location', 'address', 'phone', 8.9])

array(['name', 'location', 'address', 'phone', '8.9'], dtype='<U32')

In [19]:
# if the datatype is incovertible, it will lead to an error

# np.array(['4.6', 45,32, 'phone', 8.9], dtype='float64')

In [20]:
# creating an array of lenght 10 filled with zero values

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# creating an array of lenght 10 filled with one values

np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.zeros((10,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
# crearting array of lenght 10 with a specificed value
np.full(10, '9')

array(['9', '9', '9', '9', '9', '9', '9', '9', '9', '9'], dtype='<U1')

In [24]:
# crating a 3 by 5 array with specified value 6
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [25]:
# creating array within a certain range of values
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
# creating array specifying the starting point
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
# creating array specifying the steps
np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# crating an array of values with floating step
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [28]:
from numpy import pi

np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
# to generate number which are uniformly spaced, use 'np.linspace'
np.linspace(1,100,8)

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [30]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [31]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [32]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [33]:
# to generate an array that are uniformly distributed

np.random.random((3,3))

array([[0.20106241, 0.66760877, 0.50058981],
       [0.19489967, 0.98287391, 0.42797676],
       [0.38072513, 0.63421267, 0.79502611]])

In [34]:
# To create a 3 by 3 array of normally distributed random values with mean 0 and standard variation 1
np.random.normal(0,1,(3,3))

array([[-1.01898536,  0.76311775, -0.88982502],
       [ 1.11300975,  1.678459  , -0.2598601 ],
       [-1.06020745, -1.93248836,  0.39973451]])

In [35]:
# create random integers numbers 
np.random.randint(0,10)

4

In [36]:
np.random.randint(1,50000)

43846

In [37]:
val = np.random.randint(0,10,7)
val

array([5, 0, 8, 9, 1, 8, 3])

In [38]:
val = np.random.randint(0,10,(4,2,3))
val

array([[[0, 0, 6],
        [9, 9, 9]],

       [[8, 0, 5],
        [6, 8, 5]],

       [[8, 3, 0],
        [1, 3, 0]],

       [[3, 2, 6],
        [5, 8, 3]]])

In [39]:
val.ndim

3

In [41]:
# TO CREATE an identity array. identity matrix are matrix who diagonal are 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# 1dim array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [43]:
# a.shape
# a.reshape(2,3)
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
# 2d array
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
b = np.arange(24).reshape(2,3,4)
print(b)
# b.ndim

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


3

In [68]:
# if array is too large to be printed, numpy automatically skips the central partof the array
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [51]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(10000))

In [52]:
# To always give a constant value
np.random.seed(2)
x1 = np.random.randint(10, size=6)
x1

array([8, 8, 6, 2, 8, 7])

In [53]:
# Basic operations 

a = np.array([20,30,40,50])
a

array([20, 30, 40, 50])

In [54]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [55]:
# Subtraction operation 
c = a-b
c

array([20, 29, 38, 47])

In [56]:
# power operation
b**2

array([0, 1, 4, 9])

In [57]:
# multiplication 
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [59]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

A*B    #Elementwise product column by colun


array([[2, 0],
       [0, 4]])

In [60]:
A

array([[1, 1],
       [0, 1]])

In [61]:
B

array([[2, 0],
       [3, 4]])

In [62]:
# For matrix product first row by first column

A@B

array([[5, 4],
       [3, 4]])

In [63]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [64]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))

a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [65]:
b += a
b

array([[3.33033482, 3.20464863, 3.61927097],
       [3.29965467, 3.26682728, 3.62113383]])

In [67]:
#  a += b 

In [69]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
# b.dtype.name
a.dtype.name

'int32'

In [70]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [71]:
d = np.exp(c*1j)
d


array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [72]:
d.dtype

dtype('complex128')

In [73]:
c.dtype

dtype('float64')

In [75]:
a = np.random.random((2,3))
a

array([[0.52914209, 0.13457995, 0.51357812],
       [0.18443987, 0.78533515, 0.85397529]])

In [76]:
# To sum the element of an array
a.sum()

3.0010504669907965

In [77]:
# To find the min the element of an array
a.min()

0.13457994534493356

In [78]:
a.max()

0.8539752926394888

In [79]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
# sum of each column
b.sum(axis=0)

array([12, 15, 18, 21])

In [81]:
#  min of each row
b.min(axis=1)

array([0, 4, 8])

In [83]:
# cumulative sum of each row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [84]:
# Universal functions
# they are Mathematical functions such as cos, sin and exponent (exp)

In [86]:
b = np.arange(3)
b

array([0, 1, 2])

In [87]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [88]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [89]:
c = np.array([2,-1,4])
np.add(b,c)

array([2, 0, 6])

In [90]:
xm = np.array([1,2,3,4,5,11,12,13,14,15,16])
xm +xm

array([ 2,  4,  6,  8, 10, 22, 24, 26, 28, 30, 32])

In [91]:
xm*xm

array([  1,   4,   9,  16,  25, 121, 144, 169, 196, 225, 256])

In [92]:
xm + 10

array([11, 12, 13, 14, 15, 21, 22, 23, 24, 25, 26])

In [95]:
-(0.5 * xm +1)**2

array([ -2.25,  -4.  ,  -6.25,  -9.  , -12.25, -42.25, -49.  , -56.25,
       -64.  , -72.25, -81.  ])

In [96]:
# using built-in function

# using np.add()
np.add(xm,9)

array([10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 25])

In [97]:
np.abs(xm)

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 16])

In [98]:
ab = np.array([-2,-1,0,1,2])
np.abs(ab)

array([2, 1, 0, 1, 2])

In [101]:
comp = np.array([3-4J, 4-3J, 2+0j, 0+1j])
np.abs(comp)

array([5., 5., 2., 1.])

In [102]:
tri = np.linspace(0, np.pi, 5)
tri

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [103]:
np.sin(tri)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [104]:
acr = [-1,0,1]
np.arcsin(acr)

array([-1.57079633,  0.        ,  1.57079633])

INDEXING, SLICING AND ITERATING OF AN ARRAY


In [105]:
a = np.arange(3)
a

array([0, 1, 2])

In [106]:
# finding the element at index 2
a[2]

2

In [107]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [108]:
a[2]

8

In [109]:
#  equivalent to a [0:6:2] = -1000; from start to position 6
# exclusive, set every 2nd element to -1000
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [112]:
# negative index allow you to print the array from the back
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [113]:
b = np.arange(10)**3
b

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [114]:
c = b.reshape(2,5)

In [118]:
c


array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [119]:
c[0,3]

27

In [121]:
c[0,-2]

27

In [122]:
c[0,-2 ]= 1  # it should replace what's in position -2  to 1
c

array([[  0,   1,   8,   1,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [123]:
# slicing

c[1:]

array([[125, 216, 343, 512, 729]], dtype=int32)

In [124]:
c[:2]

array([[  0,   1,   8,   1,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [125]:
a[2:5]

array([-1000,    27, -1000], dtype=int32)

In [126]:
c[2:5]

array([], shape=(0, 5), dtype=int32)

In [129]:
#  slice a array from the beginning to the end at a step of 2
a[::-2]

array([729, 343, 125,  27,   1], dtype=int32)

In [128]:
a[::]

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [130]:
a[:]

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [131]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [133]:
x = np.array([[9,1,1,8],
           [8,5,7,2],
           [6,5,6,7],
           [2,4,5,6]])
x

array([[9, 1, 1, 8],
       [8, 5, 7, 2],
       [6, 5, 6, 7],
       [2, 4, 5, 6]])

In [134]:
x[::-1]

array([[2, 4, 5, 6],
       [6, 5, 6, 7],
       [8, 5, 7, 2],
       [9, 1, 1, 8]])

In [135]:
x[:2, :2]   #NB: :2 is row, :2 is column

array([[9, 1],
       [8, 5]])

In [138]:
x[:3, ::2] #NB: :3 is row, ::2 is column

# i.e, print row till index 3 and  all column with step of 2

array([[9, 1],
       [8, 7],
       [6, 6]])

In [139]:
x[:, 0]

array([9, 8, 6, 2])

In [140]:
x[0, :]

array([9, 1, 1, 8])

In [141]:
xw = x[:3, ::2]
xw

array([[9, 1],
       [8, 7],
       [6, 6]])

In [152]:
# Iterating of an array
def f(x,y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
# b

# to print all the row

# for row in b:
#     print(row)
    
for element in b.flat:
    print(element)
    
    

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [143]:
#  Reshaping of an array
ar = np.arange(1,13)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
# let check it shape
ar.shape

(12,)

In [153]:
# checking the dimension
ar.ndim

1

In [154]:
# reshapint it to a 3 by 4 array
ar = ar.reshape(3,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
ax = np.array([1,2,3,4,5,6])
ax

array([1, 2, 3, 4, 5, 6])

In [156]:
ax.reshape(6,1) 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [157]:
# reshape horizontally by placing np.newaxis along the row
ax[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6]])

In [158]:
# reshape vertically by placing np.newaxis along the column
ax[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [167]:
# for multidimension

mt = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
mt

# mt.ndim

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [165]:
mtrow = mt[np.newaxis,:]
mtrow

# mtrow.ndim


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [174]:
mtcol = mt[:,np.newaxis]
mtcol

# mtcol.ndim


array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]]])

In [170]:
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 8., 0., 5.],
       [0., 4., 0., 1.],
       [5., 2., 1., 2.]])

In [171]:
a.shape

(3, 4)

In [172]:
a.ravel() # return the array, flattened it from a 2 ndim to 1 dim

array([4., 8., 0., 5., 0., 4., 0., 1., 5., 2., 1., 2.])

In [176]:
# we can reshape the flattened array
a.reshape(6,2)

array([[4., 8.],
       [0., 5.],
       [0., 4.],
       [0., 1.],
       [5., 2.],
       [1., 2.]])

In [175]:
# to transpose
a.T

array([[4., 0., 5.],
       [8., 4., 2.],
       [0., 0., 1.],
       [5., 1., 2.]])

In [177]:
a.T.shape

(4, 3)

In [178]:
a.resize((2,6))

In [179]:
a

array([[4., 8., 0., 5., 0., 4.],
       [0., 1., 5., 2., 1., 2.]])

In [180]:
a.reshape(3,-1)

array([[4., 8., 0., 5.],
       [0., 4., 0., 1.],
       [5., 2., 1., 2.]])

In [181]:
#  ARRAY CONCATENATION
x = np.array([1,2,3,4,5,6])
y = np.array([7,8,9,10,11,12])
z = np.array([13,14,15,1,6,1,7,18])

np.concatenate([x,y,z]) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  1,  6,
        1,  7, 18])

In [184]:
twodim1 = np.array([[1,2,3,4,5],[6,7,8,9,23]])
twodim2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
onedim = np.array([21,22,23,24,25])
twodim1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 23]])

In [185]:
np.concatenate([twodim1, twodim2], axis=0)  # row 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 23],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [186]:
np.concatenate([twodim1, twodim2], axis=1)   #column

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 23, 16, 17, 18, 19, 20]])

In [187]:
#  ARRAY STACKING

In [190]:
# vstack is used when concatenating array eith diff dim, but the same col
b = np.vstack([onedim, twodim1])
print('onedim',onedim, "\n")
print('twodim',twodim1, "\n")

onedim [21 22 23 24 25] 

twodim [[ 1  2  3  4  5]
 [ 6  7  8  9 23]] 



In [197]:
# hstack is used when concatenating array with diff dim, but the same row
b = np.vstack([twodim1, onedim])
print('twodim1',twodim1, "\n")
print('onedim',onedim, "\n")

twodim1 [[ 1  2  3  4  5]
 [ 6  7  8  9 23]] 

onedim [21 22 23 24 25] 



In [198]:
# dstack will concatenate by joing row to row
xy = np.dstack([twodim1,twodim2])
print(xy)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [23 20]]]


In [199]:
xy.shape

(2, 5, 2)

In [200]:
w = np.floor(10*np.random.random((2,2)))
w

array([[3., 4.],
       [2., 6.]])

In [201]:
e = np.floor(10*np.random.random((2,2)))
e

array([[4., 5.],
       [3., 7.]])

In [202]:
np.vstack((w,e))

array([[3., 4.],
       [2., 6.],
       [4., 5.],
       [3., 7.]])

In [203]:
np.hstack((w,e))

array([[3., 4., 4., 5.],
       [2., 6., 3., 7.]])

In [206]:
# spliting an array
a = np.floor(10*np.random.random((2,12)))
a

array([[5., 1., 7., 9., 5., 8., 3., 5., 4., 4., 7., 5.],
       [9., 5., 0., 3., 8., 4., 0., 2., 0., 9., 9., 8.]])

In [209]:
np.hsplit(a,3)

[array([[5., 1., 7., 9.],
        [9., 5., 0., 3.]]),
 array([[5., 8., 3., 5.],
        [8., 4., 0., 2.]]),
 array([[4., 4., 7., 5.],
        [0., 9., 9., 8.]])]

In [210]:
# split a after the third and fourth column
np.hsplit(a,(3,4))

[array([[5., 1., 7.],
        [9., 5., 0.]]),
 array([[9.],
        [3.]]),
 array([[5., 8., 3., 5., 4., 4., 7., 5.],
        [8., 4., 0., 2., 0., 9., 9., 8.]])]

In [4]:
# spliting of array ny slicing the first four values and five
xy = np.array([1,2,3,4,5,11,12,13,14,15,16])
x1,x2,x3,x4 = np.split(xy, (2,5,9))
print(x1,x2,x3,x4)

[1 2] [3 4 5] [11 12 13 14] [15 16]


In [212]:
# spliting of array ny slicing the first six values
xy = np.array([1,2,3,4,5,11,12,13,14,15,16])
x1,x2 = np.split(xy, (6,))
print(x1,x2)

[ 1  2  3  4  5 11] [12 13 14 15 16]


In [213]:
# spliting of array ny slicing the first four values and the next first three
xy = np.array([1,2,3,4,5,11,12,13,14,15,16])
x1,x2, x3 = np.split(xy, (4,7))
print(x1,x2,x3)

[1 2 3 4] [ 5 11 12] [13 14 15 16]


In [214]:
# spliting a multidimension array
xx = np.arange(16).reshape((4,4))
xx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [216]:
# np.hsplit along columns starting from the second column
first, second = np.hsplit(xx, [2])
print("the first split\n", first)
print("the second split\n", second)

the first split
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
the second split
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [217]:
first, second, third = np.hsplit(xx, [2,3])
print("the first split\n", first)
print("the second split\n", second)
print("the third split\n", third)

the first split
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
the second split
 [[ 2]
 [ 6]
 [10]
 [14]]
the third split
 [[ 3]
 [ 7]
 [11]
 [15]]


In [223]:
xy = np.arange(30)
xy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [224]:
first, second, third = np.hsplit(xy, [2,3])
print("the first split\n", first)
print("the second split\n", second)
print("the third split\n", third)

the first split
 [0 1]
the second split
 [2]
the third split
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29]
